.TH GELF_GETSYMINFO 3 2025-12-30 "Libelf" "Libelf Programmer's Manual"

.SH NAME
gelf_getsyminfo \- Retrieve class\-independent additional symbol information
from the symbol table at the given index

.SH SYNOPSIS
.nf
.B #include <gelf.h>

.BI "GElf_Syminfo *gelf_getsyminfo (Elf_Data *" data ", int " ndx ", GElf_Syminfo *" dst ");"

.SH DESCRIPTION
Copy the additional symbol information entry from
.I data
at index
.I ndx
into the class\-independent
.B GElf_Syminfo
structure pointed to by
.IR dst .

.I data
should be associated with an ELF section with type
.B SHT_SUNW_syminfo
and data type
.BR ELF_T_SYMINFO .
These types are Sun/Solaris extensions and are not typically used in GNU/Linux
ELF files.

.SH PARAMETERS
.TP
.I data
Pointer to an
.B Elf_Data
for a section with type
.B SHT_SUNW_syminfo
and data type
.BR ELF_T_SYMINFO .

.TP
.I ndx
Zero\-based index of the additional symbol table information entry within
.IR data .

.TP
.I dst
Pointer to a caller\-provided structure for storing the additional symbol
information entry.  Must not be NULL.

.SH RETURN VALUE
On success, this function copies the requested additional symbol information
entry into
.I *dst
and returns
.IR dst .
On failure, NULL is returned and elf_errno is set.  If
.I data
is NULL, then NULL is returned without setting elf_errno.

.SH SEE ALSO
.BR gelf_getsym (3),
.BR gelf_update_syminfo (3),
.BR libelf (3),
.BR elf (5)

.SH ATTRIBUTES
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR gelf_getsyminfo ()
T}	Thread safety	MT-Safe
.TE

.SH REPORTING BUGS
Report bugs to <elfutils-devel@sourceware.org> or https://sourceware.org/bugzilla/.
