.TH GELF_UPDATE_DYN 3 2025-12-30 "Libelf" "Libelf Programmer's Manual"

.SH NAME
gelf_update_dyn \- Update class\-independent information in the dynamic table at the given index

.SH SYNOPSIS
.nf
.B #include <gelf.h>

.BI "int gelf_update_dyn (Elf_Data *" data ", int " ndx ", GElf_Dyn *" src ");"

.SH DESCRIPTION
Copy a class\-independent dynamic table entry from
.I src
into the
.B SHT_DYNAMIC
section associated with
.I data
at index
.IR ndx .

.SH PARAMETERS
.TP
.I data
Pointer to an
.B Elf_Data
associated with a section with type
.BR SHT_DYNAMIC .
.I data->d_type
should be
.BR ELF_T_DYN .

.TP
.I ndx
Zero\-based index of the dynamic table entry to be updated within
.IR data .

.TP
.I src
Pointer to a caller\-provided dynamic table entry.  For
.B ELFCLASS32
binaries,
.B d_tag
should be able to fit within a signed 32-bit value
while
.B d_val
and
.B d_ptr
should be able to fit within unsigned 32-bit values.
.I src
must not be NULL.

.SH RETURN VALUE
On success, this function returns a non-zero value and updates
the dynamic table entry at index
.I ndx
in
.IR data .
The dynamic table associated with
.I data
is flagged with
.BR ELF_F_DIRTY .
On failure, zero is returned and elf_errno is set.  If
.I data
is NULL, then zero is returned and elf_errno is not set.

.SH SEE ALSO
.BR gelf_getdyn (3),
.BR libelf (3),
.BR elf (5)

.SH ATTRIBUTES
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR gelf_update_dyn ()
T}	Thread safety	MT-Safe
.TE

.SH REPORTING BUGS
Report bugs to <elfutils-devel@sourceware.org> or https://sourceware.org/bugzilla/.
